### ISSUE TITLE
404 error in solr.log

### ISSUE THREAD

**Issue by rmbrich** [lucidworks/solr-scale-tk#16]
Hi, 
I'm having some trouble launching nodes with the toolkit. I pulled the latest version of this project and had to make a couple updates to the fabfile. 

First, the script kept launching instances based on **ami-5d126438** which looks to be an older PV image. I modified it to use **ami-7b669d16**, the latest HVM image released June 10.

Second, for my use case the VPC is private and instances are not publicly addressed. So, I modified the script to obtain the private IPs of the hosts instead of the public DNS (changed `inst.public_dns_name` to `inst.private_ip_address` on line 253). This seems to work fine but I don't know if it may have broken something else in the setup.

After these changes I was able to run `new_zk_ensemble` and spin up a ZK cluster with no issues. After this, `new_solrcloud` also appears to work, but I noticed the admin site not working correctly (some 404s in the Network console) so I checked the Solr logs. I spun up two solr nodes for this test and both had the same issue (from solr.log):

```
2016-08-10 15:18:34.035 INFO  (zkCallback-5-thread-1-processing-n:<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-////W3C////DTD XHTML 1.0 Transitional////EN"
         "http:////www.w3.org//TR//xhtml1//DTD//xhtml1-transitional.dtd">
<html xmlns="http:////www.w3.org//1999//xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found<//title>
 <//head>
 <body>
  <h1>404 - Not Found<//h1>
 <//body>
<//html>:8984_solr)
```

Full solr.log below. I saw "zkCallback" in this message and thought maybe something is wrong with the zookeeper cluster. I checked the logs for all 3 zookeeper nodes and they seemed normal. I'm at a loss for what to check next.

Any ideas on what might be wrong?

Thanks.

```
2016-08-10 15:18:32.868 INFO  (main) [   ] o.e.j.u.log Logging initialized @450ms
2016-08-10 15:18:33.097 INFO  (main) [   ] o.e.j.s.Server jetty-9.2.13.v20150730
2016-08-10 15:18:33.110 WARN  (main) [   ] o.e.j.s.h.RequestLogHandler !RequestLog
2016-08-10 15:18:33.112 INFO  (main) [   ] o.e.j.d.p.ScanningAppProvider Deployment monitor [file:/home/ec2-user/solr-5.5.1/cloud84/contexts/] at interval 0
2016-08-10 15:18:33.578 INFO  (main) [   ] o.e.j.w.StandardDescriptorProcessor NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
2016-08-10 15:18:33.587 WARN  (main) [   ] o.e.j.s.SecurityHandler ServletContext@o.e.j.w.WebAppContext@6321e813{/solr,file:/home/ec2-user/solr-5.5.1/cloud84/solr-webapp/webapp/,STARTING}{/home/ec2-user/solr-5.5.1/cloud84/solr-webapp/webapp} has uncovered http methods for path: /
2016-08-10 15:18:33.600 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter SolrDispatchFilter.init(): WebAppClassLoader=319977154@131276c2
2016-08-10 15:18:33.615 INFO  (main) [   ] o.a.s.c.SolrResourceLoader JNDI not configured for solr (NoInitialContextEx)
2016-08-10 15:18:33.615 INFO  (main) [   ] o.a.s.c.SolrResourceLoader using system property solr.solr.home: /home/ec2-user/solr-5.5.1/cloud84/solr
2016-08-10 15:18:33.616 INFO  (main) [   ] o.a.s.c.SolrResourceLoader new SolrResourceLoader for directory: '/home/ec2-user/solr-5.5.1/cloud84/solr'
2016-08-10 15:18:33.616 INFO  (main) [   ] o.a.s.c.SolrResourceLoader JNDI not configured for solr (NoInitialContextEx)
2016-08-10 15:18:33.616 INFO  (main) [   ] o.a.s.c.SolrResourceLoader using system property solr.solr.home: /home/ec2-user/solr-5.5.1/cloud84/solr
2016-08-10 15:18:33.627 INFO  (main) [   ] o.a.s.c.c.SolrZkClient Using default ZkCredentialsProvider
2016-08-10 15:18:33.647 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2016-08-10 15:18:33.722 INFO  (zkCallback-1-thread-1) [   ] o.a.s.c.c.ConnectionManager Watcher org.apache.solr.common.cloud.ConnectionManager@7e7328d3 name:ZooKeeperConnection Watcher:10.176.55.13:2181,10.176.55.11:2181,10.176.55.12:2181/nav-qa-solr got event WatchedEvent state:SyncConnected type:None path:null path:null type:None
2016-08-10 15:18:33.722 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2016-08-10 15:18:33.722 INFO  (main) [   ] o.a.s.c.c.SolrZkClient Using default ZkACLProvider
2016-08-10 15:18:33.729 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Loading solr.xml from SolrHome (not found in ZooKeeper)
2016-08-10 15:18:33.732 INFO  (main) [   ] o.a.s.c.SolrXmlConfig Loading container configuration from /home/ec2-user/solr-5.5.1/cloud84/solr/solr.xml
2016-08-10 15:18:33.795 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Config-defined core root directory: /home/ec2-user/solr-5.5.1/cloud84/solr
2016-08-10 15:18:33.819 INFO  (main) [   ] o.a.s.c.CoreContainer New CoreContainer 1543148593
2016-08-10 15:18:33.820 INFO  (main) [   ] o.a.s.c.CoreContainer Loading cores into CoreContainer [instanceDir=/home/ec2-user/solr-5.5.1/cloud84/solr]
2016-08-10 15:18:33.820 WARN  (main) [   ] o.a.s.c.CoreContainer Couldn't add files from /home/ec2-user/solr-5.5.1/cloud84/solr/lib to classpath: /home/ec2-user/solr-5.5.1/cloud84/solr/lib
2016-08-10 15:18:33.832 INFO  (main) [   ] o.a.s.h.c.HttpShardHandlerFactory created with socketTimeout : 600000,connTimeout : 60000,maxConnectionsPerHost : 20,maxConnections : 10000,corePoolSize : 0,maximumPoolSize : 2147483647,maxThreadIdleTime : 5,sizeOfQueue : -1,fairnessPolicy : false,useRetries : false,
2016-08-10 15:18:34.004 INFO  (main) [   ] o.a.s.u.UpdateShardHandler Creating UpdateShardHandler HTTP client with params: socketTimeout=600000&connTimeout=60000&retry=true
2016-08-10 15:18:34.007 INFO  (main) [   ] o.a.s.l.LogWatcher SLF4J impl is org.slf4j.impl.Log4jLoggerFactory
2016-08-10 15:18:34.008 INFO  (main) [   ] o.a.s.l.LogWatcher Registering Log Listener [Log4j (org.slf4j.impl.Log4jLoggerFactory)]
2016-08-10 15:18:34.008 INFO  (main) [   ] o.a.s.c.ZkContainer Zookeeper client=10.176.55.13:2181,10.176.55.11:2181,10.176.55.12:2181/nav-qa-solr
2016-08-10 15:18:34.017 INFO  (main) [   ] o.a.s.c.ZkController zkHost includes chroot
2016-08-10 15:18:34.017 INFO  (main) [   ] o.a.s.c.c.SolrZkClient Using default ZkCredentialsProvider
2016-08-10 15:18:34.017 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2016-08-10 15:18:34.022 INFO  (zkCallback-4-thread-1) [   ] o.a.s.c.c.ConnectionManager Watcher org.apache.solr.common.cloud.ConnectionManager@7193334c name:ZooKeeperConnection Watcher:10.176.55.13:2181,10.176.55.11:2181,10.176.55.12:2181 got event WatchedEvent state:SyncConnected type:None path:null path:null type:None
2016-08-10 15:18:34.024 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2016-08-10 15:18:34.024 INFO  (main) [   ] o.a.s.c.c.SolrZkClient Using default ZkACLProvider
2016-08-10 15:18:34.030 INFO  (main) [   ] o.a.s.c.ZkController Added new OnReconnect listener org.apache.solr.cloud.ZkController$6@8f4ea7c
2016-08-10 15:18:34.031 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2016-08-10 15:18:34.035 INFO  (zkCallback-5-thread-1-processing-n:<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-////W3C////DTD XHTML 1.0 Transitional////EN"
         "http:////www.w3.org//TR//xhtml1//DTD//xhtml1-transitional.dtd">
<html xmlns="http:////www.w3.org//1999//xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found<//title>
 <//head>
 <body>
  <h1>404 - Not Found<//h1>
 <//body>
<//html>:8984_solr) [   ] o.a.s.c.c.ConnectionManager Watcher org.apache.solr.common.cloud.ConnectionManager@5fe1ac64 name:ZooKeeperConnection Watcher:10.176.55.13:2181,10.176.55.11:2181,10.176.55.12:2181/nav-qa-solr got event WatchedEvent state:SyncConnected type:None path:null path:null type:None
2016-08-10 15:18:34.035 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2016-08-10 15:18:34.075 INFO  (main) [   ] o.a.s.c.ZkController Register node as live in ZooKeeper:/live_nodes/<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>:8984_solr
2016-08-10 15:18:34.079 ERROR (main) [   ] o.a.s.s.SolrDispatchFilter Could not start Solr. Check solr/home property and the logs
2016-08-10 15:18:34.100 ERROR (main) [   ] o.a.s.c.SolrCore null:java.lang.IllegalArgumentException: Invalid path string "/live_nodes/<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>:8984_solr" caused by invalid charater @55
    at org.apache.zookeeper.common.PathUtils.validatePath(PathUtils.java:99)
    at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:851)
    at org.apache.solr.common.cloud.SolrZkClient$2.execute(SolrZkClient.java:244)
    at org.apache.solr.common.cloud.SolrZkClient$2.execute(SolrZkClient.java:241)
    at org.apache.solr.common.cloud.ZkCmdExecutor.retryOperation(ZkCmdExecutor.java:60)
    at org.apache.solr.common.cloud.SolrZkClient.delete(SolrZkClient.java:241)
    at org.apache.solr.cloud.ZkController.createEphemeralLiveNode(ZkController.java:810)
    at org.apache.solr.cloud.ZkController.init(ZkController.java:656)
    at org.apache.solr.cloud.ZkController.<init>(ZkController.java:394)
    at org.apache.solr.core.ZkContainer.initZooKeeper(ZkContainer.java:112)
    at org.apache.solr.core.CoreContainer.load(CoreContainer.java:413)
    at org.apache.solr.servlet.SolrDispatchFilter.createCoreContainer(SolrDispatchFilter.java:134)
    at org.apache.solr.servlet.SolrDispatchFilter.init(SolrDispatchFilter.java:110)
    at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:138)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:852)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
    at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:186)
    at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:498)
    at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:146)
    at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
    at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:461)
    at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
    at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:609)
    at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:528)
    at org.eclipse.jetty.util.Scanner.scan(Scanner.java:391)
    at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:560)
    at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:235)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:387)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:354)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1255)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.jetty.start.Main.invokeMain(Main.java:321)
    at org.eclipse.jetty.start.Main.start(Main.java:817)
    at org.eclipse.jetty.start.Main.main(Main.java:112)

2016-08-10 15:18:34.100 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter SolrDispatchFilter.init() done
2016-08-10 15:18:34.113 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@6321e813{/solr,file:/home/ec2-user/solr-5.5.1/cloud84/solr-webapp/webapp/,AVAILABLE}{/home/ec2-user/solr-5.5.1/cloud84/solr-webapp/webapp}
2016-08-10 15:18:34.121 INFO  (main) [   ] o.e.j.s.ServerConnector Started ServerConnector@b2c9a9c{HTTP/1.1}{0.0.0.0:8984}
2016-08-10 15:18:34.121 INFO  (main) [   ] o.e.j.s.Server Started @1705ms
```

**Comment by gsingers** [comment]
@rmbrich did you ever get a fix for this?  I've been going through and updating for VPC as well and am seeing this same thing.

**Comment by rmbrich** [comment]
No, I gave up. We ended up creating Docker containers for ZK and Solr and running them in Kubernetes (the rest of our app also runs in Kubernetes).

**Comment by gsingers** [comment]
Found a clue:  My running Solr process looks like: 
`ec2-user  4122     1  0 11:28 ?        00:00:05 /home/ec2-user/jdk1.8.0_102/bin/java -server -Xms6g -Xmx6g -XX:NewRatio=3 -XX:+UseAdaptiveSizePolicy -XX:+UseParNewGC -XX:ConcGCThreads=4 -XX:ParallelGCThreads=4 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=64m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=50 -XX:CMSMaxAbortablePrecleanTime=6000 -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -verbose:gc -XX:+PrintHeapAtGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCCause -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:/home/ec2-user/solr-6.3.0/cloud84/logs/solr_gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=9 -XX:GCLogFileSize=20M -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=18984 -Dcom.sun.management.jmxremote.rmi.port=18984 -Djava.rmi.server.hostname=<?xml version="1.0" encoding="iso-8859-1"?>?<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"?         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">?<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">? <head>?  <title>404 - Not Found</title>? </head>? <body>?  <h1>404 - Not Found</h1>? </body>?</html> -DzkClientTimeout=15000 -DzkHost=172.29.1.209:2181,172.29.1.238:2181,172.29.1.254:2181/shub -Dsolr.log.dir=/home/ec2-user/solr-6.3.0/cloud84/logs -Djetty.port=8984 -DSTOP.PORT=7984 -DSTOP.KEY=solrrocks -Dhost=<?xml version="1.0" encoding="iso-8859-1"?>?<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"?         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">?<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">? <head>?  <title>404 - Not Found</title>? </head>? <body>?  <h1>404 - Not Found</h1>? </body>?</html> -Duser.timezone=UTC -Djetty.home=/home/ec2-user/solr-6.3.0/cloud84 -Dsolr.solr.home=/home/ec2-user/solr-6.3.0/cloud84/solr -Dsolr.install.dir=/home/ec2-user/solr-6.3.0 -Dsolr.autoCommit.maxTime=30000 -Dsolr.autoSoftCommit.maxTime=3000 -Xss256k -Dsolr.log.muteconsole -XX:OnOutOfMemoryError=/home/ec2-user/solr-6.3.0/bin/oom_solr.sh 8984 /home/ec2-user/solr-6.3.0/cloud84/logs -jar start.jar --module=http`

The big hint being the `-DHost` value.  We are starting Solr via `/home/ec2-user/solr-6.3.0/bin/solr start -cloud -p 8984 -d cloud84`, so something is likely wrong there.

**Comment by gsingers** [comment]
Found it: 
  solrHost = '`curl -s http://169.254.169.254/latest/meta-data/public-hostname`'

**Comment by gsingers** [comment]
Now fixed on Master.  Will update the README for private subnets in a bit.
